// <auto-generated />
namespace CourseAllocation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class semesters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(semesters));
        
        string IMigrationMetadata.Id
        {
            get { return "201511140241364_semesters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
